# Generated by Django 5.2.4 on 2025-07-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name_plural': 'Product details'},
        ),
    ]
