# Generated by Django 5.2.4 on 2025-07-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_productdetails_options'),
        ('product', '0002_alter_category_options_alter_productdetails_options_and_more'),
    ]

    operations = [
    ]
