# Generated by Django 5.2.4 on 2025-07-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_merge_20250706_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_critical_product',
            field=models.BooleanField(default=False),
        ),
    ]
