# Generated by Django 5.2.4 on 2025-07-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_productdetails_options'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arrived', 'Arrived')], default='pending', max_length=20)),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('a_date', models.DateTimeField(blank=True, null=True)),
                ('arr_date', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to='provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_products', to='provider.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'product')},
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='products',
            field=models.ManyToManyField(related_name='shipments', through='provider.ShipmentProduct', to='product.product'),
        ),
    ]
