# Generated by Django 5.2.4 on 2025-07-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_shipment_shipmentproduct_shipment_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='c_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
