# Generated by Django 5.2.4 on 2025-07-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_alter_shipment_c_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name_plural': 'shipments'},
        ),
        migrations.AlterModelOptions(
            name='shipmentproduct',
            options={'verbose_name_plural': 'shipment_products'},
        ),
        migrations.AlterModelTable(
            name='shipment',
            table='shipments',
        ),
        migrations.AlterModelTable(
            name='shipmentproduct',
            table='shipment_products',
        ),
    ]
