# Generated by Django 5.2.4 on 2025-07-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_alter_shipment_options_alter_shipmentproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='c_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
