# Generated by Django 5.2.4 on 2025-07-09 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product_created", "Product Created Notification"),
                            ("product_deleted", "Product Deleted Notification"),
                            ("product_updated", "Product Updated Notification"),
                            ("order_created", "Order Created Notification"),
                            ("shipment_created", "Shipment Created Notification"),
                        ],
                        max_length=100,
                        verbose_name="Notification Type",
                    ),
                ),
                ("created_date_time", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "to_who",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
            },
        ),
    ]
