# Generated by Django 5.2.4 on 2025-07-09 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumer', '0007_alter_orderproduct_order'),
        ('product', '0004_product_is_critical_product'),
        ('provider', '0006_provider_user_shipment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product_created', 'Product Created Notification'), ('product_deleted', 'Product Deleted Notification'), ('product_updated', 'Product Updated Notification'), ('order_created', 'Order Created Notification'), ('shipment_created', 'Shipment Created Notification')], max_length=100, verbose_name='Notification Type')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='consumer.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='product.product')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='provider.shipment')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
