# Generated by Django 5.2.4 on 2025-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('product_created', 'Product Created Notification'), ('product_deleted', 'Product Deleted Notification'), ('product_updated', 'Product Updated Notification'), ('order_created', 'Order Created Notification'), ('shipment_created', 'Shipment Created Notification'), ('order_accepted', 'Order Accepted Notification'), ('shipment_accepted', 'Shipment Accepted Notification'), ('order_rejected', 'Order Rejected Notification'), ('shipment_rejected', 'Shipment Rejected Notification')], max_length=100, verbose_name='Notification Type'),
        ),
    ]
