# Generated by Django 5.2.4 on 2025-07-05 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'conumers',
                'db_table': 'consumers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pinding'), ('canceled', 'Canceled'), ('accepted', 'Accepted'), ('arrived', 'Arrived')], default='pending', max_length=20)),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('a_date', models.DateTimeField(blank=True, null=True)),
                ('arr_date', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='consumer.consumer')),
            ],
        ),
    ]
