# Generated by Django 5.2.4 on 2025-07-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_remove_order_arr_date_order_product_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='a_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
