# Generated by Django 5.2.4 on 2025-07-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_alter_order_a_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_details',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
