# Generated by Django 5.2.4 on 2025-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_status',
            field=models.BooleanField(default=True),
        ),
    ]
